version: "3.8"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     # change to POSTGRES_HOST="database"
  #     - .env
  #   depends_on:
  #     - database

volumes:
  data:
