// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbconnection

import (
	"database/sql"
	"time"
)

type Base struct {
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        int64        `json:"id"`
}

type Post struct {
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	ID          int64        `json:"id"`
	Title       string       `json:"title"`
	UserID      int64        `json:"user_id"`
	SubreaditID int64        `json:"subreadit_id"`
	Text        string       `json:"text"`
}

type PostComment struct {
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	ID        int64         `json:"id"`
	PostID    int64         `json:"post_id"`
	UserID    int64         `json:"user_id"`
	Text      string        `json:"text"`
	ParentID  sql.NullInt64 `json:"parent_id"`
}

type PostCommentVote struct {
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
	UserID        int64        `json:"user_id"`
	Value         int32        `json:"value"`
	PostCommentID int64        `json:"post_comment_id"`
}

type PostVote struct {
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    int64        `json:"user_id"`
	Value     int32        `json:"value"`
	PostID    int64        `json:"post_id"`
}

type Subreadit struct {
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
}

type SubreaditUser struct {
	SubreaditID int64  `json:"subreadit_id"`
	UserID      int64  `json:"user_id"`
	Role        string `json:"role"`
}

type Time struct {
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type User struct {
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
}

type UserReadPost struct {
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    int64        `json:"user_id"`
	PostID    int64        `json:"post_id"`
	ReadAt    time.Time    `json:"read_at"`
}

type Vote struct {
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    int64        `json:"user_id"`
	Value     int32        `json:"value"`
}
