// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbconnection

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) error
	CreatePostComment(ctx context.Context, arg CreatePostCommentParams) (PostComment, error)
	// Post Comments
	CreatePostCommentVote(ctx context.Context, arg CreatePostCommentVoteParams) error
	// Posts
	CreatePostVote(ctx context.Context, arg CreatePostVoteParams) error
	CreateSubreadit(ctx context.Context, name string) (Subreadit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserReadPost(ctx context.Context, arg CreateUserReadPostParams) error
	DeletePost(ctx context.Context, arg DeletePostParams) error
	FindPostById(ctx context.Context, id int64) (FindPostByIdRow, error)
	FindPostCommentById(ctx context.Context, id int64) (PostComment, error)
	FindPostCommentVoteById(ctx context.Context, arg FindPostCommentVoteByIdParams) (PostCommentVote, error)
	FindPostVoteById(ctx context.Context, arg FindPostVoteByIdParams) (PostVote, error)
	FindSubreaditById(ctx context.Context, id int64) (Subreadit, error)
	FindSubreaditByName(ctx context.Context, name string) (Subreadit, error)
	FindSubreaditUser(ctx context.Context, arg FindSubreaditUserParams) (UserSubreaditsRow, error)
	FindUserById(ctx context.Context, id int64) (User, error)
	FindUserByName(ctx context.Context, username string) (User, error)
	GetPostCommentCount(ctx context.Context, postID int64) (int64, error)
	GetPostCommentTotalVoteValue(ctx context.Context, postCommentID int64) (int64, error)
	GetPostComments(ctx context.Context, postID int64) ([]GetPostCommentsRow, error)
	GetPostTotalVoteValue(ctx context.Context, postID int64) (int64, error)
	GetPosts(ctx context.Context) ([]GetPostsRow, error)
	GetPostsBySubreaditId(ctx context.Context, subreaditID int64) ([]GetPostsBySubreaditIdRow, error)
	GetPostsBySubreaditName(ctx context.Context, name string) ([]GetPostsBySubreaditNameRow, error)
	GetSubreaditUsersByRole(ctx context.Context, arg GetSubreaditUsersByRoleParams) ([]UserSubreaditsRow, error)
	GetSubreadits(ctx context.Context) ([]Subreadit, error)
	GetUserOverviewPostsAndComments(ctx context.Context, arg GetUserOverviewPostsAndCommentsParams) ([]GetUserOverviewPostsAndCommentsRow, error)
	GetUserReadPost(ctx context.Context, arg GetUserReadPostParams) (UserReadPost, error)
	GetUserSubreadits(ctx context.Context, userID int64) ([]UserSubreaditsRow, error)
	JoinSubreadit(ctx context.Context, arg JoinSubreaditParams) error
	LeaveSubreadit(ctx context.Context, arg LeaveSubreaditParams) error
	UpdatePostCommentText(ctx context.Context, arg UpdatePostCommentTextParams) error
	UpdatePostCommentVoteValue(ctx context.Context, arg UpdatePostCommentVoteValueParams) error
	UpdatePostVoteValue(ctx context.Context, arg UpdatePostVoteValueParams) error
}

var _ Querier = (*Queries)(nil)
